# cmakefmt: push { lineWidth = 40 }
if(A)
  if(B)
    if(C)
      if(D)
        if(E)
          if(F)
            if(G)
              if(H)
                if(I)
                  if(J)
                    message(STATUS "deep")
                  endif()
                endif()
              endif()
            endif()
          endif()
        endif()
      endif()
    endif()
  endif()
endif()
# cmakefmt: pop
