if(TRUE)
  message(STATUS "if")
endif()
foreach(item IN ITEMS a b)
  message(STATUS ${item})
endforeach()
while(FALSE)
  message(STATUS "while")
endwhile()
function(my_func)
  message(STATUS "func")
endfunction()
macro(my_macro)
  message(STATUS "macro")
endmacro()
block()
  message(STATUS "block")
endblock()
